/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bQQiQNuPFqALjXn1i5mrPi
// Component: IZmBAcfmTjEv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bQQiQNuPFqALjXn1i5mrPi/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bQQiQNuPFqALjXn1i5mrPi/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bQQiQNuPFqALjXn1i5mrPi/projectcss
import sty from "./PlasmicCustomButton.module.css"; // plasmic-import: IZmBAcfmTjEv/css

createPlasmicElementProxy;

export type PlasmicCustomButton__VariantMembers = {
  authState: "loggedIn" | "loggedOut";
};
export type PlasmicCustomButton__VariantsArgs = {
  authState?: SingleChoiceArg<"loggedIn" | "loggedOut">;
};
type VariantPropType = keyof PlasmicCustomButton__VariantsArgs;
export const PlasmicCustomButton__VariantProps = new Array<VariantPropType>(
  "authState"
);

export type PlasmicCustomButton__ArgsType = {};
type ArgPropType = keyof PlasmicCustomButton__ArgsType;
export const PlasmicCustomButton__ArgProps = new Array<ArgPropType>();

export type PlasmicCustomButton__OverridesType = {
  aNavbarLoginButton?: Flex__<"div">;
  manageAccount?: Flex__<"div">;
};

export interface DefaultCustomButtonProps {
  authState?: SingleChoiceArg<"loggedIn" | "loggedOut">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCustomButton__RenderFunc(props: {
  variants: PlasmicCustomButton__VariantsArgs;
  args: PlasmicCustomButton__ArgsType;
  overrides: PlasmicCustomButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "authState",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.authState
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"aNavbarLoginButton"}
      data-plasmic-override={overrides.aNavbarLoginButton}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.aNavbarLoginButton
      )}
      onClick={async event => {
        const $steps = {};

        $steps["goToLogin"] = true
          ? (() => {
              const actionArgs = { destination: `/login` };
              return (({ destination }) => {
                if (
                  typeof destination === "string" &&
                  destination.startsWith("#")
                ) {
                  document
                    .getElementById(destination.substr(1))
                    .scrollIntoView({ behavior: "smooth" });
                } else {
                  __nextRouter?.push(destination);
                }
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["goToLogin"] != null &&
          typeof $steps["goToLogin"] === "object" &&
          typeof $steps["goToLogin"].then === "function"
        ) {
          $steps["goToLogin"] = await $steps["goToLogin"];
        }
      }}
    >
      <div
        data-plasmic-name={"manageAccount"}
        data-plasmic-override={overrides.manageAccount}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.manageAccount,
          {
            [sty.manageAccountauthState_loggedIn]: hasVariant(
              $state,
              "authState",
              "loggedIn"
            )
          }
        )}
      >
        {hasVariant($state, "authState", "loggedIn")
          ? "Manage Account"
          : "Log in"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  aNavbarLoginButton: ["aNavbarLoginButton", "manageAccount"],
  manageAccount: ["manageAccount"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  aNavbarLoginButton: "div";
  manageAccount: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCustomButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCustomButton__VariantsArgs;
    args?: PlasmicCustomButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCustomButton__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCustomButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomButton__ArgProps,
          internalVariantPropNames: PlasmicCustomButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "aNavbarLoginButton") {
    func.displayName = "PlasmicCustomButton";
  } else {
    func.displayName = `PlasmicCustomButton.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomButton = Object.assign(
  // Top-level PlasmicCustomButton renders the root element
  makeNodeComponent("aNavbarLoginButton"),
  {
    // Helper components rendering sub-elements
    manageAccount: makeNodeComponent("manageAccount"),

    // Metadata about props expected for PlasmicCustomButton
    internalVariantProps: PlasmicCustomButton__VariantProps,
    internalArgProps: PlasmicCustomButton__ArgProps
  }
);

export default PlasmicCustomButton;
/* prettier-ignore-end */
