/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bQQiQNuPFqALjXn1i5mrPi
// Component: stIYJsu9atqI

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bQQiQNuPFqALjXn1i5mrPi/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bQQiQNuPFqALjXn1i5mrPi/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bQQiQNuPFqALjXn1i5mrPi/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: stIYJsu9atqI/css

import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: ImX566aEjGXx/icon
import ButtonIconIcon from "./icons/PlasmicIcon__ButtonIcon"; // plasmic-import: xJ-E5XY_mAXn/icon
import ButtonIcon2Icon from "./icons/PlasmicIcon__ButtonIcon2"; // plasmic-import: ALE1BOWP-O0x/icon
import ButtonIcon3Icon from "./icons/PlasmicIcon__ButtonIcon3"; // plasmic-import: 54eMpvLDAbZQ/icon

createPlasmicElementProxy;

export type PlasmicHeader__VariantMembers = {
  authState: "loggedIn" | "loggedOut";
};
export type PlasmicHeader__VariantsArgs = {
  authState?: SingleChoiceArg<"loggedIn" | "loggedOut">;
};
type VariantPropType = keyof PlasmicHeader__VariantsArgs;
export const PlasmicHeader__VariantProps = new Array<VariantPropType>(
  "authState"
);

export type PlasmicHeader__ArgsType = {};
type ArgPropType = keyof PlasmicHeader__ArgsType;
export const PlasmicHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicHeader__OverridesType = {
  container?: Flex__<"div">;
  navbar?: Flex__<"div">;
  navbarContainer?: Flex__<"div">;
  navbarContent?: Flex__<"div">;
  navbarBrand?: Flex__<"div">;
  aLogo?: Flex__<"div">;
  navbarMenu?: Flex__<"div">;
  aNavbarLink?: Flex__<"div">;
  button?: Flex__<"div">;
  aNavbarLink2?: Flex__<"div">;
  button2?: Flex__<"div">;
  aNavbarLink3?: Flex__<"div">;
  button3?: Flex__<"div">;
  aNavbarLink4?: Flex__<"div">;
  button4?: Flex__<"div">;
  searchWrapper?: Flex__<"div">;
  searchForm?: Flex__<"div">;
  searchInput?: Flex__<"div">;
  formTextInput?: Flex__<"div">;
  czegoSzukasz?: Flex__<"div">;
  searchButton?: Flex__<"div">;
  navbarInconsButtonWrapper?: Flex__<"div">;
  navbarLogin?: Flex__<"div">;
  aNavbarLoginButton?: Flex__<"div">;
  login?: Flex__<"div">;
  aNavbarSignup?: Flex__<"div">;
  signUp?: Flex__<"div">;
};

export interface DefaultHeaderProps {
  authState?: SingleChoiceArg<"loggedIn" | "loggedOut">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeader__RenderFunc(props: {
  variants: PlasmicHeader__VariantsArgs;
  args: PlasmicHeader__ArgsType;
  overrides: PlasmicHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "authState",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.authState
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"container"}
      data-plasmic-override={overrides.container}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.container
      )}
    >
      <div
        data-plasmic-name={"navbar"}
        data-plasmic-override={overrides.navbar}
        className={classNames(projectcss.all, sty.navbar)}
      >
        <div
          data-plasmic-name={"navbarContainer"}
          data-plasmic-override={overrides.navbarContainer}
          className={classNames(projectcss.all, sty.navbarContainer)}
        >
          <div
            data-plasmic-name={"navbarContent"}
            data-plasmic-override={overrides.navbarContent}
            className={classNames(projectcss.all, sty.navbarContent)}
          >
            <div
              data-plasmic-name={"navbarBrand"}
              data-plasmic-override={overrides.navbarBrand}
              className={classNames(projectcss.all, sty.navbarBrand)}
            >
              <div
                data-plasmic-name={"aLogo"}
                data-plasmic-override={overrides.aLogo}
                className={classNames(projectcss.all, sty.aLogo)}
              />
            </div>
            <div
              data-plasmic-name={"navbarMenu"}
              data-plasmic-override={overrides.navbarMenu}
              className={classNames(projectcss.all, sty.navbarMenu)}
            >
              <div
                data-plasmic-name={"aNavbarLink"}
                data-plasmic-override={overrides.aNavbarLink}
                className={classNames(projectcss.all, sty.aNavbarLink)}
              >
                <div
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.button
                  )}
                >
                  {"Catalog"}
                </div>
                <VectorIcon
                  className={classNames(projectcss.all, sty.svg__pLyyB)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"aNavbarLink2"}
                data-plasmic-override={overrides.aNavbarLink2}
                className={classNames(projectcss.all, sty.aNavbarLink2)}
              >
                <div
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.button2
                  )}
                >
                  {"About us"}
                </div>
              </div>
              <div
                data-plasmic-name={"aNavbarLink3"}
                data-plasmic-override={overrides.aNavbarLink3}
                className={classNames(projectcss.all, sty.aNavbarLink3)}
              >
                <div
                  data-plasmic-name={"button3"}
                  data-plasmic-override={overrides.button3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.button3,
                    {
                      [sty.button3authState_loggedIn]: hasVariant(
                        $state,
                        "authState",
                        "loggedIn"
                      )
                    }
                  )}
                >
                  {hasVariant($state, "authState", "loggedIn")
                    ? "MyB2B"
                    : "B2B"}
                </div>
              </div>
              <div
                data-plasmic-name={"aNavbarLink4"}
                data-plasmic-override={overrides.aNavbarLink4}
                className={classNames(projectcss.all, sty.aNavbarLink4)}
              >
                <div
                  data-plasmic-name={"button4"}
                  data-plasmic-override={overrides.button4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.button4
                  )}
                >
                  {"Help"}
                </div>
              </div>
              <div
                data-plasmic-name={"searchWrapper"}
                data-plasmic-override={overrides.searchWrapper}
                className={classNames(projectcss.all, sty.searchWrapper)}
              >
                <div
                  data-plasmic-name={"searchForm"}
                  data-plasmic-override={overrides.searchForm}
                  className={classNames(projectcss.all, sty.searchForm)}
                >
                  <div
                    data-plasmic-name={"searchInput"}
                    data-plasmic-override={overrides.searchInput}
                    className={classNames(projectcss.all, sty.searchInput)}
                  >
                    <div
                      data-plasmic-name={"formTextInput"}
                      data-plasmic-override={overrides.formTextInput}
                      className={classNames(projectcss.all, sty.formTextInput)}
                    >
                      <div
                        data-plasmic-name={"czegoSzukasz"}
                        data-plasmic-override={overrides.czegoSzukasz}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.czegoSzukasz
                        )}
                      >
                        {"Search..."}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"searchButton"}
                    data-plasmic-override={overrides.searchButton}
                    className={classNames(projectcss.all, sty.searchButton)}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"navbarInconsButtonWrapper"}
                data-plasmic-override={overrides.navbarInconsButtonWrapper}
                className={classNames(
                  projectcss.all,
                  sty.navbarInconsButtonWrapper
                )}
              >
                <ButtonIconIcon
                  className={classNames(projectcss.all, sty.svg__rcS05)}
                  role={"img"}
                />

                <ButtonIcon2Icon
                  className={classNames(projectcss.all, sty.svg__eLq1R)}
                  role={"img"}
                />

                <ButtonIcon3Icon
                  className={classNames(projectcss.all, sty.svg__ehhup)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"navbarLogin"}
                data-plasmic-override={overrides.navbarLogin}
                className={classNames(projectcss.all, sty.navbarLogin, {
                  [sty.navbarLoginauthState_loggedIn]: hasVariant(
                    $state,
                    "authState",
                    "loggedIn"
                  )
                })}
              >
                <div
                  data-plasmic-name={"aNavbarLoginButton"}
                  data-plasmic-override={overrides.aNavbarLoginButton}
                  className={classNames(projectcss.all, sty.aNavbarLoginButton)}
                >
                  <div
                    data-plasmic-name={"login"}
                    data-plasmic-override={overrides.login}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.login,
                      {
                        [sty.loginauthState_loggedIn]: hasVariant(
                          $state,
                          "authState",
                          "loggedIn"
                        )
                      }
                    )}
                  >
                    {hasVariant($state, "authState", "loggedIn")
                      ? "Manage Account"
                      : "Log in"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"aNavbarSignup"}
                  data-plasmic-override={overrides.aNavbarSignup}
                  className={classNames(projectcss.all, sty.aNavbarSignup)}
                >
                  <div
                    data-plasmic-name={"signUp"}
                    data-plasmic-override={overrides.signUp}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.signUp,
                      {
                        [sty.signUpauthState_loggedIn]: hasVariant(
                          $state,
                          "authState",
                          "loggedIn"
                        )
                      }
                    )}
                  >
                    {hasVariant($state, "authState", "loggedIn")
                      ? "Log Out"
                      : "Create account"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  container: [
    "container",
    "navbar",
    "navbarContainer",
    "navbarContent",
    "navbarBrand",
    "aLogo",
    "navbarMenu",
    "aNavbarLink",
    "button",
    "aNavbarLink2",
    "button2",
    "aNavbarLink3",
    "button3",
    "aNavbarLink4",
    "button4",
    "searchWrapper",
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton",
    "navbarInconsButtonWrapper",
    "navbarLogin",
    "aNavbarLoginButton",
    "login",
    "aNavbarSignup",
    "signUp"
  ],
  navbar: [
    "navbar",
    "navbarContainer",
    "navbarContent",
    "navbarBrand",
    "aLogo",
    "navbarMenu",
    "aNavbarLink",
    "button",
    "aNavbarLink2",
    "button2",
    "aNavbarLink3",
    "button3",
    "aNavbarLink4",
    "button4",
    "searchWrapper",
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton",
    "navbarInconsButtonWrapper",
    "navbarLogin",
    "aNavbarLoginButton",
    "login",
    "aNavbarSignup",
    "signUp"
  ],
  navbarContainer: [
    "navbarContainer",
    "navbarContent",
    "navbarBrand",
    "aLogo",
    "navbarMenu",
    "aNavbarLink",
    "button",
    "aNavbarLink2",
    "button2",
    "aNavbarLink3",
    "button3",
    "aNavbarLink4",
    "button4",
    "searchWrapper",
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton",
    "navbarInconsButtonWrapper",
    "navbarLogin",
    "aNavbarLoginButton",
    "login",
    "aNavbarSignup",
    "signUp"
  ],
  navbarContent: [
    "navbarContent",
    "navbarBrand",
    "aLogo",
    "navbarMenu",
    "aNavbarLink",
    "button",
    "aNavbarLink2",
    "button2",
    "aNavbarLink3",
    "button3",
    "aNavbarLink4",
    "button4",
    "searchWrapper",
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton",
    "navbarInconsButtonWrapper",
    "navbarLogin",
    "aNavbarLoginButton",
    "login",
    "aNavbarSignup",
    "signUp"
  ],
  navbarBrand: ["navbarBrand", "aLogo"],
  aLogo: ["aLogo"],
  navbarMenu: [
    "navbarMenu",
    "aNavbarLink",
    "button",
    "aNavbarLink2",
    "button2",
    "aNavbarLink3",
    "button3",
    "aNavbarLink4",
    "button4",
    "searchWrapper",
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton",
    "navbarInconsButtonWrapper",
    "navbarLogin",
    "aNavbarLoginButton",
    "login",
    "aNavbarSignup",
    "signUp"
  ],
  aNavbarLink: ["aNavbarLink", "button"],
  button: ["button"],
  aNavbarLink2: ["aNavbarLink2", "button2"],
  button2: ["button2"],
  aNavbarLink3: ["aNavbarLink3", "button3"],
  button3: ["button3"],
  aNavbarLink4: ["aNavbarLink4", "button4"],
  button4: ["button4"],
  searchWrapper: [
    "searchWrapper",
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton"
  ],
  searchForm: [
    "searchForm",
    "searchInput",
    "formTextInput",
    "czegoSzukasz",
    "searchButton"
  ],
  searchInput: ["searchInput", "formTextInput", "czegoSzukasz"],
  formTextInput: ["formTextInput", "czegoSzukasz"],
  czegoSzukasz: ["czegoSzukasz"],
  searchButton: ["searchButton"],
  navbarInconsButtonWrapper: ["navbarInconsButtonWrapper"],
  navbarLogin: [
    "navbarLogin",
    "aNavbarLoginButton",
    "login",
    "aNavbarSignup",
    "signUp"
  ],
  aNavbarLoginButton: ["aNavbarLoginButton", "login"],
  login: ["login"],
  aNavbarSignup: ["aNavbarSignup", "signUp"],
  signUp: ["signUp"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  container: "div";
  navbar: "div";
  navbarContainer: "div";
  navbarContent: "div";
  navbarBrand: "div";
  aLogo: "div";
  navbarMenu: "div";
  aNavbarLink: "div";
  button: "div";
  aNavbarLink2: "div";
  button2: "div";
  aNavbarLink3: "div";
  button3: "div";
  aNavbarLink4: "div";
  button4: "div";
  searchWrapper: "div";
  searchForm: "div";
  searchInput: "div";
  formTextInput: "div";
  czegoSzukasz: "div";
  searchButton: "div";
  navbarInconsButtonWrapper: "div";
  navbarLogin: "div";
  aNavbarLoginButton: "div";
  login: "div";
  aNavbarSignup: "div";
  signUp: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "container") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("container"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    navbarContainer: makeNodeComponent("navbarContainer"),
    navbarContent: makeNodeComponent("navbarContent"),
    navbarBrand: makeNodeComponent("navbarBrand"),
    aLogo: makeNodeComponent("aLogo"),
    navbarMenu: makeNodeComponent("navbarMenu"),
    aNavbarLink: makeNodeComponent("aNavbarLink"),
    button: makeNodeComponent("button"),
    aNavbarLink2: makeNodeComponent("aNavbarLink2"),
    button2: makeNodeComponent("button2"),
    aNavbarLink3: makeNodeComponent("aNavbarLink3"),
    button3: makeNodeComponent("button3"),
    aNavbarLink4: makeNodeComponent("aNavbarLink4"),
    button4: makeNodeComponent("button4"),
    searchWrapper: makeNodeComponent("searchWrapper"),
    searchForm: makeNodeComponent("searchForm"),
    searchInput: makeNodeComponent("searchInput"),
    formTextInput: makeNodeComponent("formTextInput"),
    czegoSzukasz: makeNodeComponent("czegoSzukasz"),
    searchButton: makeNodeComponent("searchButton"),
    navbarInconsButtonWrapper: makeNodeComponent("navbarInconsButtonWrapper"),
    navbarLogin: makeNodeComponent("navbarLogin"),
    aNavbarLoginButton: makeNodeComponent("aNavbarLoginButton"),
    login: makeNodeComponent("login"),
    aNavbarSignup: makeNodeComponent("aNavbarSignup"),
    signUp: makeNodeComponent("signUp"),

    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
