// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHeader,
  DefaultHeaderProps
} from "./plasmic/non_public_project/PlasmicHeader";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { sdk } from "../lib/sdk";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HeaderProps extends Omit<DefaultHeaderProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHeaderProps altogether and have
// total control over the props for your component.
export interface HeaderProps extends DefaultHeaderProps {}

function Header_(props: HeaderProps, ref: HTMLElementRefOf<"div">) {
  const [authState, setAuthState] =
    React.useState<"loggedIn" | "loggedOut">("loggedOut");

  React.useEffect(() => {
    let isMounted = true;

    const checkSession = async () => {
      try {
        // If a customer session exists, this succeeds; otherwise it throws.
        await sdk.store.customer.retrieve();

        if (isMounted) {
          setAuthState("loggedIn");
        }
      } catch {
        if (isMounted) {
          setAuthState("loggedOut");
        }
      }
    };

    void checkSession();

    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <PlasmicHeader
      container={{ ref }}
      authState={authState}
      {...props}
    />
  );
}

const Header = React.forwardRef(Header_);
export default Header;
