// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHeader,
  DefaultHeaderProps
} from "./plasmic/non_public_project/PlasmicHeader";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useRouter } from "next/router";
import { sdk } from "../lib/sdk";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HeaderProps extends Omit<DefaultHeaderProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHeaderProps altogether and have
// total control over the props for your component.
export interface HeaderProps extends DefaultHeaderProps {}

function Header_(props: HeaderProps, ref: HTMLElementRefOf<"div">) {
  const router = useRouter();
  const [authState, setAuthState] =
    React.useState<"loggedIn" | "loggedOut">("loggedOut");

  React.useEffect(() => {
    let isMounted = true;

    const checkSession = async () => {
      try {
        // If a customer session exists, this succeeds; otherwise it throws.
        await sdk.store.customer.retrieve();

        if (isMounted) {
          setAuthState("loggedIn");
        }
      } catch {
        if (isMounted) {
          setAuthState("loggedOut");
        }
      }
    };

    void checkSession();

    return () => {
      isMounted = false;
    };
  }, []);

  const handleLoginButtonClick = () => {
    // Use authState directly since button label already reflects correct state
    if (authState === "loggedIn") {
      // "Manage Account" button - redirect to /manage-account
      void router.push("/manage-account");
    } else {
      // "Log in" button - redirect to /login
      void router.push("/login");
    }
  };

  const handleSignupButtonClick = async () => {
    if (authState === "loggedIn") {
      // "Log Out" button - perform logout
      try {
        await sdk.auth.logout();
        setAuthState("loggedOut");
        // Optionally redirect to home page after logout
        void router.push("/");
      } catch (error) {
        // eslint-disable-next-line no-alert
        alert(`Logout failed: ${String(error)}`);
      }
    } else {
      // "Create account" button - redirect to /create-account
      void router.push("/create-account");
    }
  };

  return (
    <PlasmicHeader
      container={{ ref }}
      authState={authState}
      customButton={{
        onClick: handleLoginButtonClick,
      }}
      signUp={{
        onClick: handleSignupButtonClick,
      }}
      {...props}
    />
  );
}

const Header = React.forwardRef(Header_);
export default Header;
