// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicLoginPage,
  DefaultLoginPageProps
} from "./plasmic/non_public_project/PlasmicLoginPage";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useRouter } from "next/router";
import { sdk } from "../lib/sdk";
import { FetchError } from "@medusajs/js-sdk";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface LoginPageProps extends Omit<DefaultLoginPageProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultLoginPageProps altogether and have
// total control over the props for your component.
export interface LoginPageProps extends DefaultLoginPageProps {}

function LoginPage_(props: LoginPageProps, ref: HTMLElementRefOf<"div">) {
  const router = useRouter();

  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [isSubmitting, setIsSubmitting] = React.useState(false);

  const handleLogin = async (event?: { preventDefault?: () => void }) => {
    event?.preventDefault?.();

    if (!email || !password) {
      // Basic validation; you can surface this in the UI if needed.
      return;
    }

    setIsSubmitting(true);

    try {
      await sdk.auth.login("customer", "emailpass", {
        email,
        password,
      });

      setIsSubmitting(false);

      // eslint-disable-next-line no-alert
      alert("Logged in successfully.");
      void router.push("/");
    } catch (error) {
      const fetchError = error as FetchError;

      // eslint-disable-next-line no-alert
      alert(
        `Login failed: ${fetchError.statusText ?? ""} ${
          fetchError.message ?? String(error)
        }`
      );
      setIsSubmitting(false);
    }
  };

  return (
    <PlasmicLoginPage
      root={{ ref }}
      email={{
        value: email,
        onChange: (val: string) => setEmail(val),
      }}
      password={{
        value: password,
        onChange: (val: string) => setPassword(val),
      }}
      login={{
        disabled: isSubmitting,
        onClick: handleLogin,
      }}
      {...props}
    />
  );
}

const LoginPage = React.forwardRef(LoginPage_);
export default LoginPage;
